#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
#!/usr/bin/env python3
"""
Tool 11: Collision Layer Matrix Generator (#42)
Generates collision layer interaction matrix from project.godot and scenes.
Author: Jango (Lead, Tool Engineer)
"""

import os
import re
import sys
from pathlib import Path
from typing import Dict, Set, Tuple

ASHFALL_ROOT = Path(__file__).parent.parent / "games" / "ashfall"
PROJECT_GODOT = ASHFALL_ROOT / "project.godot"
SCENES_DIR = ASHFALL_ROOT / "scenes"

def parse_collision_layers() -> Dict[int, str]:
    """Parse layer names from project.godot"""
    print("📖 Reading collision layer names from project.godot...")
    
    if not PROJECT_GODOT.exists():
        print(f"❌ project.godot not found at {PROJECT_GODOT}")
        return {}
    
    content = PROJECT_GODOT.read_text(encoding="utf-8")
    
    # Parse 2d_physics/layer_N="Name"
    layer_pattern = r'2d_physics/layer_(\d+)="([^"]+)"'
    matches = re.findall(layer_pattern, content)
    
    layers = {}
    for layer_num, layer_name in matches:
        layers[int(layer_num)] = layer_name
    
    print(f"✅ Found {len(layers)} collision layers")
    for num, name in sorted(layers.items()):
        print(f"   Layer {num}: {name}")
    
    return layers

def scan_scene_files() -> Dict[str, Tuple[Set[int], Set[int]]]:
    """
    Scan .tscn files for collision_layer and collision_mask values.
    Returns: {scene_path: (layers_set, masks_set)}
    """
    print(f"\n🔍 Scanning scene files in {SCENES_DIR}...")
    
    scene_data = {}
    
    for tscn_file in SCENES_DIR.rglob("*.tscn"):
        try:
            content = tscn_file.read_text(encoding="utf-8")
            
            # Find collision_layer and collision_mask values
            layers = set()
            masks = set()
            
            # Pattern: collision_layer = 1 or collision_layer=1
            layer_matches = re.findall(r'collision_layer\s*=\s*(\d+)', content)
            for match in layer_matches:
                # Convert bitmask to layer numbers
                bitmask = int(match)
                for bit in range(32):
                    if bitmask & (1 << bit):
                        layers.add(bit + 1)  # Godot layers are 1-indexed
            
            mask_matches = re.findall(r'collision_mask\s*=\s*(\d+)', content)
            for match in mask_matches:
                bitmask = int(match)
                for bit in range(32):
                    if bitmask & (1 << bit):
                        masks.add(bit + 1)
            
            if layers or masks:
                rel_path = tscn_file.relative_to(ASHFALL_ROOT)
                scene_data[str(rel_path)] = (layers, masks)
                print(f"   {rel_path.name}: layers={layers}, masks={masks}")
        
        except Exception as e:
            print(f"⚠️  Error reading {tscn_file.name}: {e}")
    
    print(f"✅ Scanned {len(scene_data)} scenes with collision data")
    return scene_data

def build_interaction_matrix(layers: Dict[int, str], scene_data: Dict[str, Tuple[Set[int], Set[int]]]) -> Dict[Tuple[int, int], bool]:
    """
    Build matrix showing which layers interact.
    Returns: {(layer_a, layer_b): interacts}
    """
    print("\n🔨 Building collision interaction matrix...")
    
    matrix = {}
    
    # For each layer pair, check if any scene has one as layer and other as mask
    for layer_a in layers.keys():
        for layer_b in layers.keys():
            interacts = False
            
            # Check all scenes
            for scene_path, (scene_layers, scene_masks) in scene_data.items():
                # A interacts with B if:
                # - A is in collision_layer and B is in collision_mask, OR
                # - B is in collision_layer and A is in collision_mask
                if (layer_a in scene_layers and layer_b in scene_masks) or \
                   (layer_b in scene_layers and layer_a in scene_masks):
                    interacts = True
                    break
            
            matrix[(layer_a, layer_b)] = interacts
    
    return matrix

def generate_markdown_table(layers: Dict[int, str], matrix: Dict[Tuple[int, int], bool]) -> str:
    """Generate markdown table of collision matrix"""
    sorted_layers = sorted(layers.items())
    
    # Header
    lines = ["# Collision Layer Matrix", ""]
    lines.append("Generated by Tool 11: Collision Layer Matrix Generator")
    lines.append("")
    lines.append("**Legend:**")
    lines.append("- ✅ = Layers interact (one is in layer, other is in mask)")
    lines.append("- ❌ = No interaction detected")
    lines.append("")
    
    # Table header
    header = "| Layer |"
    separator = "|-------|"
    
    for num, name in sorted_layers:
        header += f" {name} |"
        separator += "--------|"
    
    lines.append(header)
    lines.append(separator)
    
    # Table rows
    for row_num, row_name in sorted_layers:
        row = f"| **{row_name}** |"
        
        for col_num, col_name in sorted_layers:
            if matrix.get((row_num, col_num), False):
                row += " ✅ |"
            else:
                row += " ❌ |"
        
        lines.append(row)
    
    lines.append("")
    lines.append("## Layer Details")
    lines.append("")
    
    for num, name in sorted_layers:
        lines.append(f"### Layer {num}: {name}")
        lines.append("")
        lines.append(f"**Interacts with:**")
        
        interactions = []
        for other_num, other_name in sorted_layers:
            if matrix.get((num, other_num), False) and num != other_num:
                interactions.append(other_name)
        
        if interactions:
            for interaction in interactions:
                lines.append(f"- {interaction}")
        else:
            lines.append("- *(no interactions detected)*")
        
        lines.append("")
    
    return "\n".join(lines)

def generate_console_table(layers: Dict[int, str], matrix: Dict[Tuple[int, int], bool]):
    """Print collision matrix to console"""
    sorted_layers = sorted(layers.items())
    
    print("\n" + "="*80)
    print("🎯 COLLISION LAYER INTERACTION MATRIX")
    print("="*80)
    
    # Print header
    print("\nLegend: ✅ = Interacts | ❌ = No interaction\n")
    
    # Calculate column widths
    max_name_len = max(len(name) for _, name in sorted_layers)
    col_width = max(max_name_len, 10)
    
    # Print header row
    print(" " * (col_width + 3), end="")
    for num, name in sorted_layers:
        print(f"{name[:8]:^8}", end=" ")
    print()
    
    # Print separator
    print("-" * (col_width + 3 + (9 * len(sorted_layers))))
    
    # Print matrix rows
    for row_num, row_name in sorted_layers:
        print(f"{row_name:<{col_width}} | ", end="")
        
        for col_num, col_name in sorted_layers:
            symbol = " ✅  " if matrix.get((row_num, col_num), False) else " ❌  "
            print(symbol, end=" ")
        
        print()
    
    print("\n" + "="*80)
    
    # Print layer details
    print("\n📋 LAYER INTERACTION DETAILS")
    print("-"*80)
    
    for num, name in sorted_layers:
        interactions = []
        for other_num, other_name in sorted_layers:
            if matrix.get((num, other_num), False) and num != other_num:
                interactions.append(other_name)
        
        if interactions:
            print(f"\n{name} (Layer {num}):")
            print(f"  → Interacts with: {', '.join(interactions)}")
        else:
            print(f"\n{name} (Layer {num}):")
            print(f"  → No interactions detected")

def main():
    print("🔧 Tool 11: Collision Layer Matrix Generator")
    print("="*80)
    
    # Parse layer names
    layers = parse_collision_layers()
    
    if not layers:
        print("❌ No collision layers found in project.godot")
        return 1
    
    # Scan scene files
    scene_data = scan_scene_files()
    
    if not scene_data:
        print("⚠️  No scenes with collision data found")
        print("   (This is OK if you haven't created physics objects yet)")
    
    # Build interaction matrix
    matrix = build_interaction_matrix(layers, scene_data)
    
    # Print to console
    generate_console_table(layers, matrix)
    
    # Generate markdown
    markdown = generate_markdown_table(layers, matrix)
    
    output_path = ASHFALL_ROOT / "docs" / "COLLISION-MATRIX.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    
    print(f"\n📄 Markdown report written to:")
    print(f"   {output_path}")
    print("\n✨ Done!")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
