#!/usr/bin/env python3
"""
Tool 12: Frame Data CSV Pipeline - Import (#43)
Imports frame data from CSV and generates .tres resource files.
Author: Jango (Lead, Tool Engineer)
"""

import csv
import sys
from pathlib import Path
from typing import Dict, List

ASHFALL_ROOT = Path(__file__).parent.parent / "games" / "ashfall"
INPUT_CSV = ASHFALL_ROOT / "data" / "frame-data.csv"
OUTPUT_DIR = ASHFALL_ROOT / "resources" / "moves"

def load_csv_data() -> List[Dict[str, str]]:
    """Load frame data from CSV"""
    print("📖 Reading frame data CSV...")
    
    if not INPUT_CSV.exists():
        print(f"❌ CSV not found: {INPUT_CSV}")
        print("   Run export-frame-data.py first to generate the CSV.")
        return []
    
    moves = []
    
    try:
        with INPUT_CSV.open('r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                moves.append(row)
        
        print(f"✅ Loaded {len(moves)} moves from CSV")
        
    except Exception as e:
        print(f"❌ Error reading CSV: {e}")
        return []
    
    return moves

def generate_move_resource(move: Dict[str, str]) -> str:
    """Generate .tres resource file content for a move"""
    
    # Extract fields with defaults
    character = move.get("character", "Unknown")
    move_name = move.get("move_name", "Unnamed")
    move_id = move.get("move_id", "move")
    damage = move.get("damage", "0")
    startup = move.get("startup", "0")
    active = move.get("active", "0")
    recovery = move.get("recovery", "0")
    hitstun = move.get("hitstun", "0")
    blockstun = move.get("blockstun", "0")
    meter_gain = move.get("meter_gain", "0")
    move_type = move.get("move_type", "normal")
    notes = move.get("notes", "")
    
    # Generate Godot resource format
    tres_content = f'''[gd_resource type="Resource" script_class="MoveData" load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/data/move_data.gd" id="1_move_data"]

[resource]
script = ExtResource("1_move_data")
character = "{character}"
move_name = "{move_name}"
move_id = "{move_id}"
damage = {damage}
startup_frames = {startup}
active_frames = {active}
recovery_frames = {recovery}
hitstun_frames = {hitstun}
blockstun_frames = {blockstun}
meter_gain = {meter_gain}
move_type = "{move_type}"
notes = "{notes}"
'''
    
    return tres_content

def generate_move_data_script():
    """Generate the MoveData class script if it doesn't exist"""
    script_path = ASHFALL_ROOT / "scripts" / "data" / "move_data.gd"
    
    if script_path.exists():
        print(f"   ℹ️  MoveData script already exists at {script_path}")
        return
    
    script_content = '''extends Resource
class_name MoveData
## Frame data resource for a single move
## Generated by Frame Data CSV Pipeline (Tool 12)

@export var character: String = ""
@export var move_name: String = ""
@export var move_id: String = ""

@export_group("Frame Data")
@export var damage: int = 0
@export var startup_frames: int = 0
@export var active_frames: int = 0
@export var recovery_frames: int = 0
@export var hitstun_frames: int = 0
@export var blockstun_frames: int = 0

@export_group("Properties")
@export var meter_gain: int = 0
@export var move_type: String = "normal"  # normal, special, super
@export var notes: String = ""

func get_total_frames() -> int:
\treturn startup_frames + active_frames + recovery_frames

func is_plus_on_block() -> bool:
\treturn blockstun_frames > (active_frames + recovery_frames)

func get_frame_advantage_on_block() -> int:
\treturn blockstun_frames - (active_frames + recovery_frames)

func get_frame_advantage_on_hit() -> int:
\treturn hitstun_frames - (active_frames + recovery_frames)
'''
    
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content, encoding="utf-8")
    print(f"   ✅ Created MoveData script at {script_path}")

def import_moves(moves: List[Dict[str, str]]):
    """Import moves and generate .tres files"""
    print(f"\n🔨 Generating .tres resource files...")
    
    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Generate MoveData script first
    generate_move_data_script()
    
    generated_count = 0
    
    # Group by character
    by_character: Dict[str, List[Dict[str, str]]] = {}
    for move in moves:
        char = move.get("character", "Unknown")
        if char not in by_character:
            by_character[char] = []
        by_character[char].append(move)
    
    # Generate resource files
    for character, char_moves in by_character.items():
        char_dir = OUTPUT_DIR / character.lower()
        char_dir.mkdir(parents=True, exist_ok=True)
        
        print(f"\n📁 {character} ({len(char_moves)} moves)")
        
        for move in char_moves:
            move_id = move.get("move_id", "move")
            move_name = move.get("move_name", "Unnamed")
            
            # Generate .tres file
            tres_content = generate_move_resource(move)
            
            # Write to file
            output_file = char_dir / f"{move_id}.tres"
            output_file.write_text(tres_content, encoding="utf-8")
            
            print(f"   ✅ {move_name} → {output_file.name}")
            generated_count += 1
    
    print(f"\n✨ Generated {generated_count} move resource files")
    print(f"📂 Location: {OUTPUT_DIR}")

def main():
    print("🔧 Tool 12: Frame Data CSV Pipeline - IMPORT")
    print("="*80)
    
    # Load CSV
    moves = load_csv_data()
    
    if not moves:
        print("\n❌ No moves to import.")
        return 1
    
    # Import and generate resources
    import_moves(moves)
    
    print("\n" + "="*80)
    print("✅ Import complete!")
    print("\n💡 USAGE:")
    print("   1. Edit frame data in: games/ashfall/data/frame-data.csv")
    print("   2. Run: python tools/import-frame-data.py")
    print("   3. Resources updated in: games/ashfall/resources/moves/")
    print("   4. Use in code: preload('res://resources/moves/kael/lp.tres')")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
